# Generated by Django 4.2.4 on 2023-09-14 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TallerMecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_taller', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('numero_telefono', models.CharField(max_length=15)),
                ('horarios_atencion', models.TextField()),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
                'db_table': 'taller',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tallermecanico')),
            ],
            options={
                'verbose_name': 'Fecha',
                'verbose_name_plural': 'Fechas',
                'db_table': 'Fecha',
                'ordering': ['id'],
            },
        ),
    ]
