# Generated by Django 4.2.4 on 2023-09-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cita_options_alter_cita_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallermecanico',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tallermecanico',
            name='horarios_atencion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tallermecanico',
            name='numero_telefono',
            field=models.CharField(max_length=200),
        ),
    ]
