# Generated by Django 4.2.4 on 2023-09-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_tallermecanico_atencion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tallermecanico',
            name='direction',
        ),
        migrations.AddField(
            model_name='tallermecanico',
            name='descripcion',
            field=models.CharField(max_length=500, null=True, verbose_name='Descripcion'),
        ),
    ]
