# Generated by Django 4.2.5 on 2023-09-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='añadir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Nombre del taller')),
                ('direction', models.CharField(max_length=50, null=True, verbose_name='Direccion del taller')),
                ('number', models.CharField(max_length=15, null=True, verbose_name='Telefono del taller')),
                ('atencion', models.TimeField(null=True, verbose_name='Horario de atencion')),
                ('description', models.CharField(max_length=2000, null=True, verbose_name='Descripcion del taller')),
            ],
            options={
                'verbose_name': 'Añadir',
                'verbose_name_plural': 'Añadir',
                'db_table': 'Nuevo_taller',
                'ordering': ['id'],
            },
        ),
    ]
