# Generated by Django 4.2.5 on 2023-09-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_añadir'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='añadir',
            table='Taller_nuevo',
        ),
    ]
