# Generated by Django 4.2.4 on 2023-09-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_añadir_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='añadir',
        ),
    ]
