# Generated by Django 4.2.6 on 2023-10-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_añadir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='linea',
            field=models.CharField(choices=[('corolla', 'Corolla'), ('mazda3', 'Mazda 3')], max_length=50, null=True, verbose_name='Linea'),
        ),
        migrations.AlterField(
            model_name='car',
            name='marca',
            field=models.CharField(choices=[('toyota', 'Toyota'), ('mazda', 'Mazda')], max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tipo',
            field=models.CharField(choices=[('gasolina', 'Gasolina'), ('gas', 'Gas'), ('diésel', 'Diésel')], max_length=20, null=True, verbose_name='Tipo'),
        ),
    ]
