# Generated by Django 4.2.4 on 2023-11-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_car_linea_alter_car_marca_alter_car_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='linea',
            field=models.CharField(choices=[('Corolla', 'Corolla'), ('Camry', 'Camry'), ('Prius', 'Prius'), ('Mazda3', 'Mazda 3'), ('Mazda6', 'Mazda 6'), ('CX-5', 'CX-5')], max_length=50, null=True, verbose_name='Linea'),
        ),
        migrations.AlterField(
            model_name='car',
            name='marca',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Mazda', 'Mazda')], max_length=50, null=True, verbose_name='Marca'),
        ),
    ]
