# Generated by Django 4.2.4 on 2023-11-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_car_linea_alter_car_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='marca',
            field=models.CharField(choices=[('toyota', 'Toyota'), ('mazda', 'Mazda')], max_length=50, null=True, verbose_name='Marca'),
        ),
    ]
