# Generated by Django 4.2.4 on 2023-11-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_car_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='marca',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Mazda', 'Mazda')], max_length=50, null=True, verbose_name='Marca'),
        ),
    ]
