# Generated by Django 4.2.4 on 2023-11-13 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_car_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_part', models.CharField(choices=[('motor', 'Motor')], max_length=50, null=True, verbose_name='Parte')),
                ('symptom', models.CharField(choices=[('ruido', 'Ruido')], max_length=50, null=True, verbose_name='Sintoma')),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
