# Generated by Django 4.2.4 on 2023-11-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_diagnostico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnostico',
            options={'ordering': ['id'], 'verbose_name': 'Diagnostico', 'verbose_name_plural': 'Diagnosticos'},
        ),
        migrations.AlterModelTable(
            name='diagnostico',
            table='diagnostico',
        ),
    ]
