# Generated by Django 4.2.4 on 2023-11-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_servicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['id'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelTable(
            name='servicio',
            table='servicio',
        ),
    ]
