# Generated by Django 4.2.6 on 2023-11-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_diagnostico_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='car_part',
            field=models.CharField(choices=[('motor', 'Motor'), ('transmision', 'Transmision'), ('frenos', 'Frenos'), ('suspension', 'Suspension'), ('aire_acondicionado', 'Aire acondicionado'), ('luces', 'Luces'), ('direccion', 'Direccion')], max_length=50, null=True, verbose_name='Parte'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='symptom',
            field=models.CharField(choices=[('ruido', 'Ruido'), ('vibracion', 'Vibracion'), ('rebote', 'Rebote'), ('no_enfria', 'No enfria'), ('parpadeo', 'Parpadeo')], max_length=50, null=True, verbose_name='Sintoma'),
        ),
    ]
